repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

      - id: check-added-large-files


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: python-compile
        name: Check python syntax (py_compile)
        entry: python -m py_compile
        language: system
        files: \.py$
      - id: utf8-check-custom
        name: Ensure files are valid UTF-8
        entry: powershell -NoProfile -ExecutionPolicy Bypass -File check_utf8.ps1
        language: system
        files: \.py$
