repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.1.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --follow-imports=skip, --exclude game/ollama_ai.py]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-r, game]



  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.9
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]

  - repo: https://github.com/pytest-dev/pytest
    rev: 7.4.2
    hooks:
      - id: pytest
        additional_dependencies: [pytest-cov]