"""
maps.py

This file contains the game maps and art.
"""

# Tile pixel art
GRASS_TILE_ART = ["GgGg", "gGgG", "GgGg", "gGgG"]
WATER_TILE_ART = ["BbBb", "bBbB", "BbBb", "bBbB"]

TILE_ART_MAP = {
    "G": GRASS_TILE_ART,
    "W": WATER_TILE_ART,
}

GAME_MAP = [
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGWWWWWWWWWWWWWWWWWWGGGGGGGGGGGG",
    "GGGGGGGGWWWWWWWWWWWWWWWWWWWWWWGGGGGGGGGG",
    "GGGGGGGWWWWWWWWWWWWWWWWWWWWWWWWGGGGGGGGG",
    "GGGGGGWWWWWWWWWWWWWWWWWWWWWWWWWWGGGGGGGG",
    "GGGGGGWWWWWWWWWWWWWWWWWWWWWWWWWWGGGGGGGG",
    "GGGGGGWWWWWWWWWWWWWWWWWWWWWWWWWWGGGGGGGG",
    "GGGGGGWWWWWWWWWWWWWWWWWWWWWWWWWWGGGGGGGG",
    "GGGGGGWWWWWWWWWWWWWWWWWWWWWWWWWWGGGGGGGG",
    "GGGGGGWWWWWWWWWWWWWWWWWWWWWWWWWWGGGGGGGG",
    "GGGGGGGGWWWWWWWWWWWWWWWWWWWWWWGGGGGGGGGG",
    "GGGGGGGGGGWWWWWWWWWWWWWWWWWWGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
]

MOOD_GLYPHS = {
    "neutral": [],  # No glyph for neutral
    "happy": ["..^.^..", ".(o.o).", ".(   ).", r"..\_/..."],  # Simple happy face
    "angry": ["..>.<..", ".(o.o).", ".(---).", r"../\_\.."],  # Simple angry face
    "tired": ["..-.-..", ".(o.o).", ".(   ).", r"..\_/..."],  # Simple tired face
}
