name: CI Guardians

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r game/requirements.txt

      - name: Check formatting with black
        run: black --check .

      - name: Check import order with isort
        run: isort --check-only .

      - name: Lint with pylint
        run: pylint game

      - name: Run tests
        run: pytest
